# Generated by Django 2.0.6 on 2018-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DarkskyCurrentWeather',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('precip_intensity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DarkSky_current_weather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DarkskyHistoricalWeatherData',
            fields=[
                ('time', models.IntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('precip_intensity', models.FloatField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'DarkSky_historical_weather_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DarkskyHourlyWeatherPrediction',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('time', models.IntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('precip_intensity', models.FloatField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DarkSky_hourly_weather_prediction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FareStages',
            fields=[
                ('stoppointid', models.IntegerField(primary_key=True, serialize=False)),
                ('stage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fare_stages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaticBusData',
            fields=[
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('longname', models.CharField(max_length=30)),
                ('shortname', models.CharField(max_length=30)),
                ('stoppointid', models.IntegerField(primary_key=True, serialize=False)),
                ('streetname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'static_bus_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips2017',
            fields=[
                ('dayofservice', models.CharField(blank=True, max_length=30, null=True)),
                ('tripid', models.IntegerField()),
                ('lineid', models.CharField(blank=True, max_length=10, null=True)),
                ('routeid', models.CharField(blank=True, max_length=10, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('plannedtime_arr', models.IntegerField(blank=True, null=True)),
                ('plannedtime_dep', models.IntegerField(blank=True, null=True)),
                ('actualtime_arr', models.IntegerField(blank=True, null=True)),
                ('actualtime_dep', models.IntegerField(blank=True, null=True)),
                ('suppressed', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trips_2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leavetimes2017',
            fields=[
                ('dayofservice', models.CharField(blank=True, max_length=30, null=True)),
                ('progrnumber', models.IntegerField()),
                ('stoppointid', models.IntegerField(blank=True, null=True)),
                ('plannedtime_arr', models.IntegerField(blank=True, null=True)),
                ('plannedtime_dep', models.IntegerField(blank=True, null=True)),
                ('actualtime_arr', models.IntegerField(blank=True, null=True)),
                ('actualtime_dep', models.IntegerField(blank=True, null=True)),
                ('vehicleid', models.IntegerField(blank=True, null=True)),
                ('suppressed', models.IntegerField(blank=True, null=True)),
                ('lastupdate', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.ForeignKey(db_column='timestamp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='timestamp_fk', serialize=False, to='api.Trips2017')),
            ],
            options={
                'db_table': 'leavetimes_2017',
                'managed': False,
            },
        ),
    ]
