function makePredictionNow() {
    let data = {
        hour: hourNow,
        day: dayNow,
        temp: tempNow,
        rain: rainNow,
        route: document.getElementById("routesDropdown").value,
        startStop: document.getElementById("firstStop").value,
        endStop: document.getElementById("lastStop").value
    };

    fetch("https://dublinbus.icu/api/make_prediction", {
            method: "POST",
            headers: {
                "Content-Type": "application/json; charset=utf-8"
            },
            referrer: "no-referrer",
            body: JSON.stringify(data)
        })
        .then(function(response) {
            return response.json(); // Currently only returning a single value. Using JSON to allow easier extension later
        })
        .then(function(prediction) {
            document.getElementById("prediction").innerHTML = `Estimated time: <b>${prediction["result"]}</b> minutes`;
        })
        .catch(function() {
            document.getElementById("prediction").innerHTML = "Prediction server not available."
        });
}

function makePredictionToday() {
    let data = {
        hour: document.getElementById("time").value,
        day: dayNow,
        temp: tempToday,
        rain: rainToday,
        route: document.getElementById("routesDropdown").value,
        startStop: document.getElementById("firstStop").value,
        endStop: document.getElementById("lastStop").value
    };

    fetch("https://dublinbus.icu/api/make_prediction", {
            method: "POST",
            headers: {
                "Content-Type": "application/json; charset=utf-8"
            },
            referrer: "no-referrer",
            body: JSON.stringify(data)
        })
        .then(function(response) {
            return response.json();
        })
        .then(function(prediction) {
            document.getElementById("forecast").innerHTML = `Estimated time: <b>${prediction["result"]}</b> minutes`;
        })
        .catch(function() {
            document.getElementById("forecast").innerHTML = "Something has gone tits up."
        });
}


function getLatestWeather() {
    fetch("https://dublinbus.icu/api/current_weather")
        .then(function(response) {
            return response.json();
        })
        .then(function(weather) {
            tempNow = weather["temp"];
            rainNow = weather["precip_intensity"];
        })
        .then(function() {
            console.log(tempNow);
            console.log(rainNow)
        });
}

function getTodayForecast() {
    fetch("https://dublinbus.icu/api/forecast")
        .then(function(response) {
            return response.json();
        })
        .then(function(forecast) {
            tempToday = forecast["temp"];
            rainToday = forecast["rain"];
            console.log(tempToday, rainToday);
        })
}

function routesDropdown() {
    allBuses.forEach(function(routeNum) {
        let item = document.createElement("option");
        item.textContent = routeNum;
        item.value = routeNum;
        document.getElementById("routesDropdown").appendChild(item);
    });
}

function getStopLocation(stopNumber) {
    fetch("https://dublinbus.icu/api/stop_location", {
            method: "POST",
            headers: {
                "Content-Type": "application/json; charset=utf-8"
            },
            referrer: "no-referrer",
            body: JSON.stringify({
                stop: stopNumber
            })
        })
        .then(function(response) {
            return response.json();
        })
        .then(function(myLatLng) {
            new google.maps.Marker({
                position: myLatLng,
                map: map,
            });
        });
}

google.charts.load('current', {
    'packages': ['corechart']
});

let predictions = []; // the values for this array will be generated by the prediciton function
predictions = [20, 20, 21, 40, 45, 30, 27, 25, 31, 34, 40, 45, 43, 37, 29, 23, 20, 19, 19, "July 17"];

function drawChart() {
    let data = google.visualization.arrayToDataTable([
        ['Hour of Day', 'Journey Length (mins)'],
        ['5 AM', predictions[0]],
        ['6 AM', predictions[1]],
        ['7 AM', predictions[2]],
        ['8 AM', predictions[3]],
        ['9 AM', predictions[4]],
        ['10 AM', predictions[5]],
        ['11 AM', predictions[6]],
        ['12 Noon', predictions[7]],
        ['1 PM', predictions[8]],
        ['2 PM', predictions[9]],
        ['3 PM', predictions[10]],
        ['4 PM', predictions[11]],
        ['5 PM', predictions[12]],
        ['6 PM', predictions[13]],
        ['7 PM', predictions[14]],
        ['8 PM', predictions[15]],
        ['9 PM', predictions[16]],
        ['10 PM', predictions[17]],
        ['11 PM', predictions[18]]
    ]);

    let options = {
        animation: {
            duration: 2000,
            easing: 'out',
            startup: true
        },
        title: 'Hourly Journey Travel Times ' + predictions[19],
        axisTitlesPosition: 'out',
        backgroundColor: 'transparent',
        curveType: 'function',
        hAxis: {
            title: "Time of Day"
        },
        legend: {
            position: 'in'
        },
        vAxis: {
            format: 'decimal',
            title: '\nJourney Time (mins)',
            gridlines: {
                color: 'transparent'
            }
        },
        lineWidth: 10,
        colors: ['#6699FF'],
        is3D: true
    };

    let chart = new google.visualization.LineChart(document.getElementById('chart_div'));

    chart.draw(data, options);
}


// Taken directly from Brynja's map code:

// Global variable for map
var map;


// Reference from https://developers.google.com/maps/documentation/javascript/adding-a-google-map
function initMap() { // Function that initialize and adds the map to the website
    var Dublin = {
        lat: 53.349805,
        lng: -6.290310
    } // The location of Dublin
    map = new google.maps.Map( // The map, centered at Dublin
        document.getElementById('map'), {
            zoom: 12,
            center: Dublin
        });
}




/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *                                                                        *
 * GLOBAL VARIABLES. THERE ARE BETTER WAYS TO DO THIS. THIS IS TEMPORARY  *
 *                                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

const today = new Date();
const hourNow = today.getHours();
const dayNow = today.getDay();
let tempNow;
let rainNow;
let tempToday;
let rainToday;

const allBuses = [
    "1",
    "102",
    "104",
    "11",
    "111",
    "114",
    "116",
    "118",
    "120",
    "122",
    "123",
    "13",
    "130",
    "14",
    "140",
    "142",
    "145",
    "14C",
    "15",
    "150",
    "151",
    "15A",
    "15B",
    "16",
    "161",
    "16C",
    "17",
    "17A",
    "18",
    "184",
    "185",
    "220",
    "236",
    "238",
    "239",
    "25",
    "25A",
    "25B",
    "25D",
    "25X",
    "26",
    "27",
    "270",
    "27A",
    "27B",
    "27X",
    "29A",
    "31",
    "31A",
    "31B",
    "31D",
    "32",
    "32X",
    "33",
    "33A",
    "33B",
    "33X",
    "37",
    "38",
    "38A",
    "38B",
    "38D",
    "39",
    "39A",
    "4",
    "40",
    "40B",
    "40D",
    "41",
    "41A",
    "41B",
    "41C",
    "41X",
    "42",
    "42D",
    "43",
    "44",
    "44B",
    "45A",
    "46A",
    "46E",
    "47",
    "49",
    "51D",
    "51X",
    "53",
    "54A",
    "56A",
    "59",
    "61",
    "63",
    "65",
    "65B",
    "66",
    "66A",
    "66B",
    "66X",
    "67",
    "67X",
    "68",
    "68A",
    "68X",
    "69",
    "69X",
    "7",
    "70",
    "70D",
    "75",
    "757",
    "76",
    "76A",
    "77A",
    "77X",
    "79",
    "79A",
    "7A",
    "7B",
    "7D",
    "83",
    "83A",
    "84",
    "84A",
    "84X",
    "9"
];

// Do these things as soon as page loads:
document.addEventListener('DOMContentLoaded', function() {
    routesDropdown();
    getLatestWeather();
    getTodayForecast();
});